server {
    listen       80;
    location / {
        root   /app/web/;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    location ~ \.php$ {
        try_files $uri /index.html;
        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        include /etc/nginx/fastcgi_params;
        add_header Allow "GET, POST, HEAD" always;
        if ( $request_method !~ ^(GET|POST|HEAD)$ ) {
        return 405;
        }
   }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /app/web/;
    }
}
